name: End-to-end tests
on: 
  push:
    branches-ignore:
      - master  # Ignore pushes to master, only trigger on feature branches
permissions:
  contents: write
  pull-requests: write
jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
  merge-branch:
    runs-on: ubuntu-24.04
    needs: cypress-run
    steps:
      - name: Merge Branch into Master
        run: |
          # Set up Git
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Checkout master and merge the branch
          git pull
          git checkout master
          git merge --no-ff --allow-unrelated-histories "${{ github.ref_name }}" -m "Auto-merging ${{ github.ref_name }} into master" 
          # Push the changes
          git push origin master
      - name: Delete Branch After Merge
        if: success()
        run: |
          echo "Deleting branch ${{ github.ref_name }}..."
          git push origin --delete "${{ github.ref_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
